### ISSUE TITLE
Freeze after Dropping Long Sequences preprocessing (KTO)

### ISSUE THREAD

**Issue by e-p-armstrong** [axolotl-ai-cloud/axolotl#2207]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Training should proceed with dataset preprocessing completing successfully.

### Current behaviour

Currently training freezes after dropping long sequences in data preprocessing. This happens with and without deepspeed, on old and new versions, between different instances on Runpod (A40s). Model is based on Llama 3.

Traceback 1 (new version, no deepspeed):
```
Generating train split: 13602 examples [00:00, 69507.67 examples/s]
Generating train split: 4244 examples [00:00, 72640.79 examples/s]
tokenizer_config.json: 100%|_________________________________________________________________________________________________________________________________________________________________________________| 50.9k/50.9k [00:00<00:00, 86.8MB/s]
tokenizer.json: 100%|________________________________________________________________________________________________________________________________________________________________________________________| 17.2M/17.2M [00:00<00:00, 39.5MB/s]
special_tokens_map.json: 100%|___________________________________________________________________________________________________________________________________________________________________________________| 449/449 [00:00<00:00, 1.40MB/s]
[2024-12-19 23:26:05,204] [DEBUG] [axolotl.load_tokenizer:296] [PID:524] [RANK:0] EOS: 128001 / <|end_of_text|>
[2024-12-19 23:26:05,204] [DEBUG] [axolotl.load_tokenizer:297] [PID:524] [RANK:0] BOS: 128000 / <|begin_of_text|>
[2024-12-19 23:26:05,204] [DEBUG] [axolotl.load_tokenizer:298] [PID:524] [RANK:0] PAD: 128001 / <|end_of_text|>
[2024-12-19 23:26:05,204] [DEBUG] [axolotl.load_tokenizer:299] [PID:524] [RANK:0] UNK: None / None
Mapping RL Dataset: 100%|_________________________________________________________________________________________________________________________________________________________________________| 13602/13602 [00:00<00:00, 14703.54 examples/s]
Dropping Long Sequences (num_proc=96): 100%|________________________________________________________________________________________________________________________________________________________| 13602/13602 [00:22<00:00, 607.78 examples/s]
[2024-12-19 23:26:30,891] [WARNING] [axolotl.load_split:182] [PID:524] [RANK:0] Dropped 8 long samples from dataset index 0
Mapping RL Dataset: 100%|___________________________________________________________________________________________________________________________________________________________________________| 4244/4244 [00:00<00:00, 14497.84 examples/s]
Dropping Long Sequences (num_proc=96): 100%|__________________________________________________________________________________________________________________________________________________________| 4244/4244 [00:18<00:00, 227.58 examples/s]
```

Traceback 2( older versio (axolotlai/axolotl-cloud:main-20241207-py3.11-cu121-2.3.1) yes deepspeed, has  bit more information)

```
[rank7]:[W1219 22:53:13.306424587 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 7]  using GPU 7 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank1]:[W1219 22:53:13.329360055 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 1]  using GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank4]:[W1219 22:53:13.334641963 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 4]  using GPU 4 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank5]:[W1219 22:53:13.418548789 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 5]  using GPU 5 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[2024-12-19 22:53:14,426] [DEBUG] [axolotl.load_tokenizer:296] [PID:2874] [RANK:0] EOS: 128001 / <|end_of_text|>
[2024-12-19 22:53:14,426] [DEBUG] [axolotl.load_tokenizer:297] [PID:2874] [RANK:0] BOS: 128000 / <|begin_of_text|>
[2024-12-19 22:53:14,426] [DEBUG] [axolotl.load_tokenizer:298] [PID:2874] [RANK:0] PAD: 128001 / <|end_of_text|>
[2024-12-19 22:53:14,426] [DEBUG] [axolotl.load_tokenizer:299] [PID:2874] [RANK:0] UNK: None / None
[2024-12-19 22:53:15,371] [WARNING] [axolotl.load_split:182] [PID:2874] [RANK:0] Dropped 8 long samples from dataset index 0
[rank0]:[W1219 22:53:16.485971513 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
```
I'm thinking that maybe the "potentially cause a hang" is at fault? But it doesn't show up in new Axo and I don't know if I am the cause of the message?

Also strangely enough, even though I don't see a ./last_run_prepared dataset output directory, on subsequent runs on the same instance it does not seem to have to tokenize everything. I ls'd and rm -rf'd just in case but it still skips that process. I want to be able to test from scratch. Is it being saved somewhere else?!

### Steps to reproduce

1. Attempt full parameter KTO train of Llama 3 with chatml.argilla on multi-GPU Nvidia
2. Observe freeze

### Config yaml

```yaml
base_model: Heralax/redacted-llama3-model
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

rl: kto
rl_beta: 0.2
kto_desirable_weight: 0.2

chat_template: chatml
datasets:
  - path: redacted1.jsonl
    ds_type: json
    data_files:
      - redacted1.jsonl
    split: train
    type: chatml.argilla
  - path: redacted2.jsonl
    ds_type: json
    data_files:
      - redacted2.jsonl
    split: train
    type: chatml.argilla

dataset_prepared_path: ./last_run_prepared
val_set_size: 0.0
output_dir: /output_dir
remove_unused_columns: false
max_steps: 500

sequence_len: 4000
sample_packing: false
pad_to_sequence_len: false
shuffle_merged_datasets: true

gradient_accumulation_steps: 16
micro_batch_size: 1
num_epochs: 2
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 5e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
remove_unused_columns: false
early_stopping_patience:
resume_from_checkpoint: 
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch: 0
eval_table_size:
eval_max_new_tokens: 
saves_per_epoch: 1

debug:
deepspeed:
fsdp:
fsdp_config:
fsdp:
fsdp_config:

special_tokens:
  pad_token: <|end_of_text|>
```

Current data format:
{"system": "redacted string", "instruction": "redacted string", "completion": "redacted string", "label": true|false}

### Possible solution

Might have to do with the "potentially cause a hang" logging on the older version with deepspeed?
Or maybe it's user error and the data format is wrong for the type and it's silently failing and hanging?

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

main/5b8fb5e939713b85340a7da25aa15d1240cb0740 (latest docker image)

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by bursteratom** [comment]
Hi @e-p-armstrong , wondering if you've encountered the same on a different gpu, like RTX3090 or H100 for example?

**Comment by e-p-armstrong** [comment]
@bursteratom Thanks for getting back to me so fast! I tried again using slightly different data settings in the config:
```
chat_template: chatml
datasets:
  - ds_type: json
    data_files:
      - redacted1.jsonl
    split: train
    type: chatml.argilla
  - ds_type: json
    data_files:
      - redacted2.jsonl
    split: train
    type: chatml.argilla
```
And it worked this time on 3X A100s and at least got past that part on 8x A40s. Strangely the A40s OOM'd during the converting modules to torch.bfloat16 phase even though they should've had more VRAM between them than the A100s? I'm guessing that's due to some messiness around batch sizes and multi GPU training, but that's another different question 😅 the main problem's solved now!

Here's the A40 traceback incase it is of interest
```
[2024-12-20 01:33:40,348] [INFO] [axolotl.load_model:1110] [PID:3136] [RANK:6] Converting modules to torch.bfloat16
Loading checkpoint shards: 100%|____________________________________________________________________________________________________________________________________________________________________________________| 2/2 [00:03<00:00,  1.94s/it]
Loading checkpoint shards: 100%|____________________________________________________________________________________________________________________________________________________________________________________| 2/2 [00:03<00:00,  1.83s/it]
Loading checkpoint shards: 100%|____________________________________________________________________________________________________________________________________________________________________________________| 2/2 [00:04<00:00,  2.00s/it]
Loading checkpoint shards: 100%|____________________________________________________________________________________________________________________________________________________________________________________| 2/2 [00:03<00:00,  1.88s/it]
[2024-12-20 01:33:40,577] [INFO] [axolotl.load_model:1077] [PID:3132] [RANK:2] cuda memory usage after model load: 14.958GB (+0.126GB cache, +1.077GB misc)
[2024-12-20 01:33:40,592] [INFO] [axolotl.load_model:1077] [PID:3134] [RANK:4] cuda memory usage after model load: 14.958GB (+0.126GB cache, +1.030GB misc)
[2024-12-20 01:33:40,595] [INFO] [axolotl.load_model:1110] [PID:3132] [RANK:2] Converting modules to torch.bfloat16
[2024-12-20 01:33:40,610] [INFO] [axolotl.load_model:1077] [PID:3131] [RANK:1] cuda memory usage after model load: 14.958GB (+0.126GB cache, +1.077GB misc)
Loading checkpoint shards: 100%|____________________________________________________________________________________________________________________________________________________________________________________| 2/2 [00:03<00:00,  1.88s/it]
[2024-12-20 01:33:40,616] [INFO] [axolotl.load_model:1110] [PID:3134] [RANK:4] Converting modules to torch.bfloat16
[2024-12-20 01:33:40,626] [INFO] [axolotl.load_model:1110] [PID:3131] [RANK:1] Converting modules to torch.bfloat16
[2024-12-20 01:33:40,715] [INFO] [axolotl.load_model:1077] [PID:3137] [RANK:7] cuda memory usage after model load: 14.958GB (+0.126GB cache, +1.054GB misc)
[2024-12-20 01:33:40,732] [INFO] [axolotl.load_model:1110] [PID:3137] [RANK:7] Converting modules to torch.bfloat16
Loading checkpoint shards:  50%|__________________________________________________________________________________________                                                                                          | 1/2 [00:03<00:03,  3.67s/it]
[2024-12-20 01:33:41,003] [INFO] [axolotl.load_model:1077] [PID:3133] [RANK:3] cuda memory usage after model load: 14.958GB (+0.126GB cache, +1.054GB misc)
[2024-12-20 01:33:41,027] [INFO] [axolotl.load_model:1110] [PID:3133] [RANK:3] Converting modules to torch.bfloat16
Loading checkpoint shards: 100%|____________________________________________________________________________________________________________________________________________________________________________________| 2/2 [00:03<00:00,  1.95s/it]
[2024-12-20 01:33:41,310] [INFO] [axolotl.load_model:1077] [PID:3135] [RANK:5] cuda memory usage after model load: 14.958GB (+0.126GB cache, +1.054GB misc)
[2024-12-20 01:33:41,334] [INFO] [axolotl.load_model:1110] [PID:3135] [RANK:5] Converting modules to torch.bfloat16
Loading checkpoint shards: 100%|____________________________________________________________________________________________________________________________________________________________________________________| 2/2 [00:03<00:00,  1.88s/it]
[2024-12-20 01:33:43,169] [INFO] [axolotl.load_model:1077] [PID:3130] [RANK:0] cuda memory usage after model load: 29.915GB (+0.251GB cache, +1.095GB misc)
[2024-12-20 01:33:43,172] [INFO] [axolotl.load_model:1110] [PID:3130] [RANK:0] Converting modules to torch.bfloat16
[rank0]: Traceback (most recent call last):
[rank0]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank0]:   File "<frozen runpy>", line 88, in _run_code
[rank0]:   File "/workspace/axolotl/src/axolotl/cli/train.py", line 58, in <module>
[rank0]:     fire.Fire(do_cli)
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
[rank0]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire
[rank0]:     component, remaining_args = _CallAndUpdateTrace(
[rank0]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
[rank0]:     component = fn(*varargs, **kwargs)
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/axolotl/src/axolotl/cli/train.py", line 34, in do_cli
[rank0]:     return do_train(parsed_cfg, parsed_cli_args)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/axolotl/src/axolotl/cli/train.py", line 47, in do_train
[rank0]:     model, tokenizer = train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
[rank0]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/axolotl/src/axolotl/train.py", line 118, in train
[rank0]:     trainer = setup_trainer(
[rank0]:               ^^^^^^^^^^^^^^
[rank0]:   File "/workspace/axolotl/src/axolotl/utils/trainer.py", line 528, in setup_trainer
[rank0]:     return trainer_builder.build(total_num_steps)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/axolotl/src/axolotl/core/trainer_builder.py", line 2238, in build
[rank0]:     dpo_trainer = trainer_cls(
[rank0]:                   ^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/transformers/utils/deprecation.py", line 165, in wrapped_func
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/trl/trainer/kto_trainer.py", line 477, in __init__
[rank0]:     self.ref_model = create_reference_model(model)
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/trl/models/modeling_base.py", line 626, in create_reference_model
[rank0]:     ref_model = deepcopy(model)
[rank0]:                 ^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 172, in deepcopy
[rank0]:     y = _reconstruct(x, memo, *rv)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 271, in _reconstruct
[rank0]:     state = deepcopy(state, memo)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 146, in deepcopy
[rank0]:     y = copier(x, memo)
[rank0]:         ^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 231, in _deepcopy_dict
[rank0]:     y[deepcopy(key, memo)] = deepcopy(value, memo)
[rank0]:                              ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 172, in deepcopy
[rank0]:     y = _reconstruct(x, memo, *rv)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 297, in _reconstruct
[rank0]:     value = deepcopy(value, memo)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 172, in deepcopy
[rank0]:     y = _reconstruct(x, memo, *rv)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 271, in _reconstruct
[rank0]:     state = deepcopy(state, memo)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 146, in deepcopy
[rank0]:     y = copier(x, memo)
[rank0]:         ^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 231, in _deepcopy_dict
[rank0]:     y[deepcopy(key, memo)] = deepcopy(value, memo)
[rank0]:                              ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 172, in deepcopy
[rank0]:     y = _reconstruct(x, memo, *rv)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 297, in _reconstruct
[rank0]:     value = deepcopy(value, memo)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 172, in deepcopy
[rank0]:     y = _reconstruct(x, memo, *rv)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 271, in _reconstruct
[rank0]:     state = deepcopy(state, memo)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 146, in deepcopy
[rank0]:     y = copier(x, memo)
[rank0]:         ^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 231, in _deepcopy_dict
[rank0]:     y[deepcopy(key, memo)] = deepcopy(value, memo)
[rank0]:                              ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 172, in deepcopy
[rank0]:     y = _reconstruct(x, memo, *rv)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 297, in _reconstruct
[rank0]:     value = deepcopy(value, memo)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 172, in deepcopy
[rank0]:     y = _reconstruct(x, memo, *rv)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 271, in _reconstruct
[rank0]:     state = deepcopy(state, memo)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 146, in deepcopy
[rank0]:     y = copier(x, memo)
[rank0]:         ^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 231, in _deepcopy_dict
[rank0]:     y[deepcopy(key, memo)] = deepcopy(value, memo)
[rank0]:                              ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 172, in deepcopy
[rank0]:     y = _reconstruct(x, memo, *rv)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 297, in _reconstruct
[rank0]:     value = deepcopy(value, memo)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 172, in deepcopy
[rank0]:     y = _reconstruct(x, memo, *rv)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 271, in _reconstruct
[rank0]:     state = deepcopy(state, memo)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 146, in deepcopy
[rank0]:     y = copier(x, memo)
[rank0]:         ^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 231, in _deepcopy_dict
[rank0]:     y[deepcopy(key, memo)] = deepcopy(value, memo)
[rank0]:                              ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 172, in deepcopy
[rank0]:     y = _reconstruct(x, memo, *rv)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 297, in _reconstruct
[rank0]:     value = deepcopy(value, memo)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 172, in deepcopy
[rank0]:     y = _reconstruct(x, memo, *rv)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 271, in _reconstruct
[rank0]:     state = deepcopy(state, memo)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 146, in deepcopy
[rank0]:     y = copier(x, memo)
[rank0]:         ^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 231, in _deepcopy_dict
[rank0]:     y[deepcopy(key, memo)] = deepcopy(value, memo)
[rank0]:                              ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 172, in deepcopy
[rank0]:     y = _reconstruct(x, memo, *rv)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 297, in _reconstruct
[rank0]:     value = deepcopy(value, memo)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/copy.py", line 153, in deepcopy
[rank0]:     y = copier(memo)
[rank0]:         ^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/nn/parameter.py", line 59, in __deepcopy__
[rank0]:     result = type(self)(self.data.clone(memory_format=torch.preserve_format), self.requires_grad)
[rank0]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU
```

Since the main issue's solved now and I can just scale up the A100s it should be fine. Thanks!

**Comment by e-p-armstrong** [comment]
@bursteratom Actually it turns out that it broke on the same preprocessing step on another A40 instance I rented after running into an OOM. This was with more A40s, 9 of them. Problem is only sidestepped it's not solved though. Is there something to do with the number of GPUs that's throwing it off here?

**Comment by bursteratom** [comment]
@e-p-armstrong From our past tests we do encounter freezing on particular instances of GPU type, which gets bypassed on a new instance and usually on a different GPU type. General rule of thumb dealing with such freezing is to retry on a different GPU type, which works 100% of the time from our own experience. This is something we've been collecting information on so thank you for your reporting!

**Comment by winglian** [comment]
I think this is related to creating the reference model as that's where the stacktrace step is

` self.ref_model = create_reference_model(model)`

**Comment by deter3** [comment]
I had the same problem . Here are my findings: 
1.  4 instances of A40 , deepspeed , working fine 
2. 5 instances of A40 , deepspeed , not working (change the instances did not resolve the problem)
3. 6 instances of A40 , deepspeed , working fine

**Comment by rlanday** [comment]
I just ran into this issue trying to do QLoRA + FSDP + sequence parallelism (degree 4) training on an 8x H200 cluster. I just tried an 8x H100 cluster where I was able to get training to start successfully (with SP degree 8) but I was hoping I could get better performance with a lower degree of SP on server with more memory.

These are the package versions I installed on the H100 server (I assume they were the same versions on the H200 since it was only a few minutes apart, but I didn’t write them down):

> Successfully installed DataProperty-1.1.0 PyJWT-2.10.1 absl-py-2.2.2 accelerate-1.6.0 addict-2.4.0 adlfs-2024.12.0 aiobotocore-2.22.0 aiofiles-23.2.1 aiohappyeyeballs-2.6.1 aiohttp-3.11.18 aioitertools-0.12.0 aiosignal-1.3.2 annotated-types-0.7.0 antlr4-python3-runtime-4.13.2 anyio-4.9.0 art-6.5 async-timeout-5.0.1 attrs-25.3.0 autoawq-0.2.7.post3 axolotl-0.9.0 axolotl-contribs-lgpl-0.0.6 axolotl-contribs-mit-0.0.3 azure-core-1.34.0 azure-datalake-store-0.0.53 azure-identity-1.22.0 azure-storage-blob-12.25.1 bitsandbytes-0.45.4 botocore-1.37.3 cachetools-5.5.2 cffi-1.17.1 chardet-5.2.0 circuitbreaker-2.1.3 click-8.1.8 cmake-4.0.0 colorama-0.4.6 coloredlogs-15.0.1 cryptography-44.0.3 datasets-3.5.0 deepspeed-0.15.4 deepspeed-kernels-0.0.1.dev1698255861 dill-0.3.8 docker-pycreds-0.4.0 einops-0.8.1 evaluate-0.4.1 fastapi-0.115.12 fastcore-1.8.1 ffmpy-0.5.0 fire-0.7.0 flash-attn-2.7.4.post1 frozenlist-1.6.0 fsspec-2024.12.0 gcsfs-2024.12.0 gitdb-4.0.12 gitpython-3.1.44 google-api-core-2.24.2 google-auth-2.40.1 google-auth-oauthlib-1.2.2 google-cloud-core-2.4.3 google-cloud-storage-3.1.0 google-crc32c-1.7.1 google-resumable-media-2.7.2 googleapis-common-protos-1.70.0 gradio-5.23.3 gradio-client-1.8.0 groovy-0.1.2 grpcio-1.71.0 grpclib-0.4.7 h11-0.16.0 h2-4.2.0 hf_transfer-0.1.9 hf_xet-1.0.0 hjson-3.1.0 hpack-4.1.0 hqq-0.2.5 httpcore-1.0.9 httpx-0.28.1 humanfriendly-10.0 hyperframe-6.1.0 immutabledict-4.2.0 isodate-0.7.2 jmespath-1.0.1 joblib-1.5.0 jsonlines-4.0.0 langdetect-1.0.9 liger-kernel-0.5.8 llvmlite-0.44.0 lm_eval-0.4.7 lxml-5.4.0 markdown-3.8 markdown-it-py-3.0.0 mbstrdecoder-1.1.4 mdurl-0.1.2 modal-0.70.5 more_itertools-10.7.0 msal-1.32.3 msal-extensions-1.3.1 msgpack-1.1.0 multidict-6.4.3 multiprocess-0.70.16 nltk-3.9.1 numba-0.61.2 numexpr-2.10.2 numpy-2.0.1 nvidia-ml-py-12.560.30 oauthlib-3.2.2 oci-2.151.0 ocifs-1.3.2 optimum-1.16.2 orjson-3.10.18 packaging-23.2 pandas-2.2.3 pathvalidate-3.2.3 peft-0.15.2 portalocker-3.1.1 propcache-0.3.1 proto-plus-1.26.1 protobuf-5.29.4 py-cpuinfo-9.0.0 pyOpenSSL-24.3.0 pyarrow-20.0.0 pyasn1-0.6.1 pyasn1-modules-0.4.2 pybind11-2.13.6 pycparser-2.22 pydantic-2.10.6 pydantic-core-2.27.2 pydub-0.25.1 pytablewriter-1.2.1 python-dotenv-1.0.1 python-multipart-0.0.20 pytz-2025.2 regex-2024.11.6 requests-oauthlib-2.0.0 responses-0.18.0 rich-14.0.0 ring-flash-attn-0.1.4 rouge-score-0.1.2 rsa-4.9.1 ruff-0.11.8 s3fs-2024.12.0 sacrebleu-2.5.1 safehttpx-0.1.6 safetensors-0.5.3 schedulefree-1.4.1 scikit-learn-1.4.2 scipy-1.15.2 semantic-version-2.10.0 sentencepiece-0.2.0 sentry-sdk-2.27.0 setproctitle-1.3.6 shellingham-1.5.4 sigtools-4.0.1 smmap-5.0.2 sniffio-1.3.1 sqlitedict-2.1.0 starlette-0.46.2 synchronicity-0.9.11 tabledata-1.3.4 tabulate-0.9.0 tcolorpy-0.1.7 tensorboard-2.19.0 tensorboard-data-server-0.7.2 termcolor-3.1.0 threadpoolctl-3.6.0 tokenizers-0.21.1 toml-0.10.2 tomlkit-0.13.2 torchao-0.9.0 tqdm-multiprocess-0.0.11 transformers-4.51.3 trl-0.17.0 typepy-1.3.4 typer-0.15.3 types-certifi-2021.10.8.3 types-toml-0.10.8.20240310 tzdata-2025.2 uvicorn-0.34.2 wandb-0.19.10 watchfiles-1.0.5 websockets-15.0.1 werkzeug-3.1.3 word2number-1.1 wrapt-1.17.2 xformers-0.0.29.post2 xxhash-3.5.0 yarl-1.20.0 yunchang-0.6.0 zstandard-0.22.0
